import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">

      <body className={inter.className}>
        <div className="relative mx-auto mt-20 max-w-7xl px-4 py-6 sm:px-6 lg:px-8">
          <div className="">
            {children}
          </div>
          <div className="fixed top-0 left-0 right-0">
            <Navbar />
          </div></div>
      </body>
    </html>
  );
}
